import { Entypo } from "@expo/vector-icons";
import { AntDesign } from "@expo/vector-icons";
import { EvilIcons } from "@expo/vector-icons";
import { Feather } from "@expo/vector-icons";
import { FontAwesome } from "@expo/vector-icons";
import { Fontisto } from "@expo/vector-icons";
import { Foundation } from "@expo/vector-icons";
import { Ionicons } from "@expo/vector-icons";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { MaterialIcons } from "@expo/vector-icons";
import { Octicons } from "@expo/vector-icons";
import { SimpleLineIcons } from "@expo/vector-icons";
import { Zocial } from "@expo/vector-icons";

export { Entypo };
export { AntDesign };
export { EvilIcons };
export { Feather };
export { FontAwesome };
export { Fontisto };
export { Foundation };
export { Ionicons };
export { MaterialCommunityIcons };
export { MaterialIcons };
export { Octicons };
export { SimpleLineIcons };
export { Zocial };